-- CREATE TABLE IF NOT EXISTS tasks (
--     task_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
--     task_title VARCHAR(50) NOT NULL,
-- 	task_description VARCHAR (255),
--     created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

--     due_at DATETIME NULL,
	
--     priority TINYINT UNSIGNED NOT NULL DEFAULT 2,
    
--     is_completed TINYINT NOT NULL DEFAULT 0,
    
--     deleted_at DATETIME NULL
-- );
