CREATE TABLE IF NOT EXISTS `users` (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(55) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    user_role ENUM('admin', 'moderator', 'user') NOT NULL DEFAULT 'user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_login DATETIME
);


CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    task_title VARCHAR(50) NOT NULL,
	task_description VARCHAR (255),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    due_at DATETIME NULL,
    priority TINYINT UNSIGNED NOT NULL DEFAULT 2,
    is_completed TINYINT NOT NULL DEFAULT 0,
    deleted_at DATETIME NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);





-- CREATE TABLE IF NOT EXISTS tasks (
--     task_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
--     task_title VARCHAR(50) NOT NULL,
-- 	task_description VARCHAR (255),
--     created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--     due_at DATETIME NULL,
--     priority TINYINT UNSIGNED NOT NULL DEFAULT 2,
--     is_completed TINYINT NOT NULL DEFAULT 0,
--     deleted_at DATETIME NULL,
--     userId BIGINT UNSIGNED NOT NULL
--     FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
-- );


-- CREATE TABLE IF NOT EXISTS `users` (
-- id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
-- userName VARCHAR(55) NOT NULL UNIQUE,
-- email VARCHAR(255) NOT NULL UNIQUE,
-- passwordHash VARCHAR(255) NOT NULL,
-- fullName VARCHAR(100),
-- is_active BOOLEAN NOT NULL DEFAULT TRUE,
-- userRole ENUM('admin', 'moderator', 'user') NOT NULL DEFAULT 'user',
-- createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
-- updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
-- last_login_at DATETIME
-- );